debug: true

server:
  port: 8080

cloud:
  aws:
    credentials:
      profileName: riiid-dev
    region:
      static: ap-northeast-2
    stack:
      auto: false

ext:
  resource-location-prefix: s3://temp-bucket-22
