debug: false

server:
  port: 8080

cloud:
  aws:
    credentials:
      profileName: riiid-dev
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com:
      hojongs: DEBUG

ext:
  resource-location-prefix: s3://temp-bucket-22/
