debug: false

server:
  port: 8080

logging:
  level:
    com.hojongs: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb

ext:
  s3:
    event-bucket-name: temp-bucket-22
